### ISSUE TITLE
NAO robot fall down just as started to move 

### ISSUE THREAD

**Issue by lcqwe** [pool-martin/NAO-with-VREP#1]
RT.
**i don't know how did it happened,and never can stand up.i check the code** `def comemorate(self):
        self.pp.goToPosture('LyingBack', 0.5)`
whether it happened because of the argument "LyingBack"?
![image](https://cloud.githubusercontent.com/assets/9477747/21296052/451c0e4a-c59d-11e6-9b6d-d8e6fe94723a.png)

## **and my trackback is:**
`Usage python motion_moveTo.py robotIP (optional default: 127.0.0.1)
================ Program Sarted ================
Connected to remote API server
[I] 2804 qimessaging.session: Session listener created on tcp://0.0.0.0:0
[I] 2804 qimessaging.transportserver: TransportServer will listen on: tcp://219.
221.196.112:2937
[I] 2804 qimessaging.transportserver: TransportServer will listen on: tcp://127.
0.0.1:2937
========== Setting Start Position ==========
================ Handles Initialization ================
-> Head for NAO
-> Left Leg for NAO
-> Right Leg for NAO
-> Left Arm for NAO
-> Right Arm for NAO
-> Left Fingers for NAO
-> Right Fingers for NAO
========== NAO is listening ==========

# R R R R R +
R U # # # . .
U . . . # # #
['U', 'R', 'U', 'R', 'R', 'R', 'R', 'R']
================ follow the path ================
Traceback (most recent call last):
  File "Labirinth.py", line 361, in <module>
    main(robotIp, clientID)
  File "Labirinth.py", line 333, in main
    nao.FollowPath(path)
  File "Labirinth.py", line 222, in FollowPath
    self.MoveTo(direction)
  File "Labirinth.py", line 175, in MoveTo
    self.SetThetaToMove(direction)
  File "Labirinth.py", line 163, in SetThetaToMove
    currentTheta = self.GetRawOrientation()
  File "Labirinth.py", line 127, in GetRawOrientation
    returnCode, NaoHandle = vrep.simxGetObjectHandle(self.vrepclientID,'NAO',vre
p.simx_opmode_oneshot_wait)
  File "C:\Program Files (x86)\V-REP3\NAO-with-VREP-master\NAO-with-VREP-master\
script\vrep.py", line 285, in simxGetObjectHandle
    return c_GetObjectHandle(clientID, objectName, ct.byref(handle), operationMo
de), handle.value
KeyboardInterrupt`
 
i manually interrupt the code. And it falling down time is when just code process to `========== 
NAO is listening ==========`

hope that your apply and thank you in advance very much.

**Comment by pool-martin** [comment]
Hi!

I think i saw this. Just decrease the screen/simulation resolution. The
Simulator just can't calculate everything in your computer with this
resolution.


Em 18/12/2016 5:45 PM, "李超" <notifications@github.com> escreveu:

RT.
i don't know how did it happened,and never can stand up.i check the code def
comemorate(self): self.pp.goToPosture('LyingBack', 0.5)
whether it happened because of the argument "LyingBack"?
[image: image]
<https://cloud.githubusercontent.com/assets/9477747/21296052/451c0e4a-c59d-11e6-9b6d-d8e6fe94723a.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pool-martin/NAO-with-VREP/issues/1>, or mute the thread

**Comment by lcqwe** [comment]
But i tried to modify the resolution from 1920*1080 to 1280*720,it didn't works.
you think if there is the other solution about this?
i really trapped in here for days,please tell me why and what i supposed to do.
thanks again!

**Comment by pool-martin** [comment]
Could you please try it using 800 x 600?
It seems that the issue happens because joint updates and window rendering (V-rep) are somehow sharing thread (or something like that causes concurrence)...
